services:
  data-prep:
    build:
      context: ./packages/data-prep
      dockerfile: Dockerfile
    # image: resonare-data-prep:latest
    command: [uv, run, app.py]
    env_file:
      - .env
    healthcheck:
      test: [CMD-SHELL, curl -f http://localhost:8000/health || exit 1]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
      - FINE_TUNING_SERVICE_URL=http://fine-tuning:8000
    volumes:
      - ./packages/data-prep/conf:/app/conf
      - ./packages/data-prep/data:/app/data
    develop:
      watch:
        # only sync source code & main script
        - action: sync
          path: ./packages/data-prep/src
          target: /app/src
        - action: sync
          path: ./packages/data-prep/app.py
          target: /app/app.py

  fine-tuning:
    build:
      context: ./packages/fine-tuning
      dockerfile: Dockerfile
    # image: resonare-fine-tuning:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - .env
    environment:
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
    volumes:
      - ./packages/fine-tuning/conf:/app/conf
      - ./packages/fine-tuning/logs:/app/logs
    healthcheck:
      test: [CMD-SHELL, curl -f http://localhost:8000/health || exit 1]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 60s
    develop:
      watch:
        # only sync source code & main script
        - action: sync
          path: ./packages/fine-tuning/src
          target: /app/src
        - action: sync
          path: ./packages/fine-tuning/main.py
          target: /app/main.py


  inference:
    build:
      context: ./packages/inference
      dockerfile: Dockerfile
    # image: resonare-inference:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - .env
    environment:
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
    volumes:
      - ./packages/inference/conf:/app/conf
    healthcheck:
      test: [CMD-SHELL, curl -f http://localhost:8000/health || exit 1]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 60s
    develop:
      watch:
        # only sync source code & main script
        - action: sync
          path: ./packages/inference/src
          target: /app/src
        - action: sync
          path: ./packages/inference/main.py
          target: /app/main.py

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    # image: resonare-frontend:latest
    command: [uv, run, streamlit, run, main.py]
    ports:
      - 8501:8501
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - DATA_PREP_URL=http://data-prep:8000
      - FINE_TUNING_URL=http://fine-tuning:8000
      - INFERENCE_URL=http://inference:8000
    volumes:
      - ./packages/frontend/conf:/app/conf
      - ./packages/frontend/assets:/app/assets
    depends_on:
      data-prep:
        condition: service_healthy
        restart: true
      fine-tuning:
        condition: service_healthy
        restart: true
      inference:
        condition: service_healthy
        restart: true
    develop:
      watch:
        - action: sync
          path: ./packages/frontend/src
          target: /app/src
        - action: sync
          path: ./packages/frontend/main.py
          target: /app/main.py
        - action: sync
          path: ./packages/frontend/pages
          target: /app/pages


networks:
  default:
    driver: bridge
