services:
  data-prep:
    build:
      context: ./packages/data-prep
      dockerfile: Dockerfile
    command: fastapi run src/app/main.py --host 0.0.0.0 --port 8000
    env_file:
      - .env
    healthcheck:
      test: [CMD-SHELL, curl -f http://localhost:8000/system/health || exit 1]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
      - FINE_TUNING_SERVICE_URL=http://unsloth-backend:8000/fine-tune/
    volumes:
      - ./packages/data-prep/conf:/app/conf
      - ./packages/data-prep/data:/app/data
      - ./packages/data-prep/logs:/app/logs
    develop:
      watch:
        # only sync source code & main script
        - action: sync
          path: ./packages/data-prep/src/app
          target: /app/src/app

  unsloth-backend:
    build:
      context: ./packages/unsloth-backend
      dockerfile: Dockerfile
    command: fastapi run src/app/main.py --host 0.0.0.0 --port 8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        # limits:
        #   memory: 8G
    env_file:
      - .env
    environment:
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
    volumes:
      - ./packages/unsloth-backend/conf:/app/conf
      - ./packages/unsloth-backend/logs:/app/logs
    healthcheck:
      test: [CMD-SHELL, curl -f http://localhost:8000/system/health || exit 1]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 60s
    develop:
      watch:
        - action: sync
          path: ./packages/data-prep/src/app
          target: /app/src/app

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    command: [uv, run, streamlit, run, main.py]
    ports:
      - 80:8501
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - DATA_PREP_URL=http://data-prep:8000
      - FINE_TUNING_SERVICE_URL=http://unsloth-backend:8000/fine-tune/
      - INFERENCE_URL=http://unsloth-backend:8000/infer/
    volumes:
      - ./packages/frontend/conf:/app/conf
      - ./packages/frontend/assets:/app/assets
    depends_on:
      data-prep:
        condition: service_healthy
        restart: true
      unsloth-backend:
        condition: service_healthy
        restart: true
    develop:
      watch:
        - action: sync
          path: ./packages/frontend/src
          target: /app/src
        - action: sync
          path: ./packages/frontend/main.py
          target: /app/main.py
        - action: sync
          path: ./packages/frontend/pages
          target: /app/pages


networks:
  default:
    driver: bridge
