[project]
dependencies = [
  "boto3>=1.37.35",
  "hydra-core>=1.3.2",
  "loguru>=0.7.3",
  "pydantic>=2.11.3",
  "python-json-logger>=3.3.0",
  "rich>=14.0.0",
  "ruff>=0.11.6",
  "tiktoken>=0.9.0",
  "transformers>=4.51.3",
]
description = "Add your description here"
name = "data-prep"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"
