version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  rich:
    format: '[%(name)s] - %(message)s'

handlers:
  console:
    class: rich.logging.RichHandler
    level: DEBUG
    # formatter: rich

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/info.log
    maxBytes: 10485760  # 10 MB

root:
  level: DEBUG
  handlers: [console, file]
