model:
  name: unsloth/Llama-3.2-1B-Instruct
  max_seq_length: 2048
  dtype:
  load_in_4bit: true
  chat_template: llama-3.1

training:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4
  warmup_steps: 5
  max_steps: 60
  learning_rate: 2e-4
  weight_decay: 0.01
  lr_scheduler_type: linear
  seed: 3407
  packing: false

output:
  dir: outputs
  report_to: none
