dataset:
  split: train
  num_proc: 2

lora:
  r: 16
  alpha: 16
  dropout: 0
  bias: none
  use_gradient_checkpointing: unsloth
  random_state: 3407
  use_rslora: false
  loftq_config:
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj

model:
  name: unsloth/gemma-3-1b-it-unsloth-bnb-4bit #unsloth/Llama-3.2-3B-Instruct-bnb-4bit   #unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit 
  max_seq_length: 2048
  dtype:
  load_in_4bit: true
  chat_template: gemma-3 #llama-3.1

training:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  warmup_steps: 5
  max_steps: 60
  learning_rate: 2e-4
  weight_decay: 0.01
  lr_scheduler_type: linear
  seed: 3407
  packing: false

output:
  dir: outputs
  report_to: none
