dataset:
  split: train
  num_proc: 2

lora:
  r: 16
  alpha: 16
  dropout: 0
  bias: none
  use_gradient_checkpointing: unsloth
  random_state: 3407
  use_rslora: false
  loftq_config:
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj

# unsloth prefix indicate that they are Unsloth dynamic 4-bit quants. 
# These models consume slightly more VRAM than standard BitsAndBytes 4-bit models but offer significantly higher accuracy.
model:
  name: unsloth/Llama-3.2-3B-Instruct-bnb-4bit
  # unsloth/llama-3-8b-Instruct-bnb-4bit
  # unsloth/Meta-Llama-3.1-8B-Instruct-unsloth-bnb-4bit
  # unsloth/Llama-3.2-1B-Instruct-unsloth-bnb-4bit
  # unsloth/Llama-3.2-3B-Instruct-unsloth-bnb-4bit
  # unsloth/gemma-3-1b-it-unsloth-bnb-4bit  
  # unsloth/gemma-3-4b-it-unsloth-bnb-4bit
  # unsloth/mistral-7b-instruct-v0.3
  
  max_seq_length: 2048
  dtype:
  load_in_4bit: true
  chat_template: llama-3.2
  # llama-3
  # llama-3.1
  # llama-3.2
  # gemma-3 
  # mistral
  # chatml

training:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  warmup_steps: 5
  max_steps: 60
  learning_rate: 2e-4
  weight_decay: 0.01
  lr_scheduler_type: linear
  seed: 3407
  packing: false

output:
  dir: outputs
  report_to: none
