model:
  name: unsloth/Llama-3.2-3B-Instruct-bnb-4bit
  #unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit  
  #unsloth/Meta-Llama-3.1-8B-Instruct-unsloth-bnb-4bit 
  #unsloth/llama-3-8b-Instruct-bnb-4bit 
  #unsloth/gemma-3-1b-it-unsloth-bnb-4bit  
  max_seq_length: 2048
  dtype:
  load_in_4bit: true
  chat_template: llama3.2
  #llama-3.2 
  #llama-3.1 
  #llama-3 
  #gemma-3 

training:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4
  warmup_steps: 5
  max_steps: 60
  learning_rate: 2e-4
  weight_decay: 0.01
  lr_scheduler_type: linear
  seed: 3407
  packing: false

output:
  dir: outputs
  report_to: none
